MDFloatLayout:
    MDLabel:
        id: task_label
        halign: "center"
        markup: True
        text: "[u][size=48][b]My Tasks[/b][/size][/u]"
        pos_hint: {'y': 0.45}
    
    ScrollView:
        pos_hint: {'center_x': 0.5,'center_y': 0.5}
        size_hint: 0.9, 0.8
    
    MDList:
        id: container
    
    MDFloatingActionButton:
        icon: "plus-thick"
        on_release: app.show_task_dialog()
        elevation_normal: 12
        pos_hint: {'x': 0.8, 'y': 0.05}